---
apiVersion: batch/v1
kind: Job
metadata:
  name: chaincodeinstantiate
spec:
  backoffLimit: 1
  template:
    metadata:
      name: chaincodeinstantiate
    spec:
      restartPolicy: "Never"
      volumes:
      - name: sharedvolume
        persistentVolumeClaim:
          claimName: shared-pvc

      containers:
      - name: chaincodeinstantiate
        image: hyperledger/fabric-tools:1.2.1
        imagePullPolicy: Always
        command: ["sh", "-c", "peer chaincode instantiate -o ord1-hlf-ord:7050 -C ${CHANNEL_NAME} -n ${CHAINCODE_NAME} -l node -v ${CHAINCODE_VERSION} -c '{"Args":[]}' -P "OR ('PeerMSP.member','Org2MSP.member'"]
        env:
        - name: CHANNEL_NAME
          value: mychannel
        - name: CHAINCODE_NAME
          value: "cc"
        - name: CHAINCODE_VERSION
          value: "1.0"
        - name: FABRIC_CFG_PATH
          value: /etc/hyperledger/fabric
        - name: CORE_PEER_MSPCONFIGPATH
          value: /shared/crypto-config/peerOrganizations/peers.svc.cluster.local/users/Admin@peers.svc.cluster.local/msp
        - name: CORE_PEER_LOCALMSPID
          value: PeerMSP
        - name: CORE_PEER_ADDRESS
          value: peer1-hlf-peer:7051
        - name: GODEBUG
          value: "netdns=go"
        volumeMounts:
        - mountPath: /shared
          name: sharedvolume
